name: spring-demo-cicd
services:
  app:
    container_name: spring-demo-cicd
    image: ${APP_IMAGE}
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env.app
    depends_on:
      flyway-migrate:
        condition: service_completed_successfully
    networks:
      - mysqldb-network

  flyway-migrate:
    image: redgate/flyway
    container_name: flyway-migrate
    env_file:
      - ../env/.env.db
    volumes:
      - ../src/main/resources/db/migrations:/flyway/migrations
    networks:
      - mysqldb-network
    # Run Flyway migrations
    entrypoint: [ "flyway", "-baselineOnMigrate=true", "-connectRetries=60", "-validateMigrationNaming=true", "migrate" ]
    healthcheck:
      test: [ "CMD-SHELL", "flyway info | grep 'No errors'" ]
      retries: 10
      interval: 5s
      timeout: 30s

  mysqldb:
    container_name: mysqldb
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env.db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysqldb-network
volumes:
  mysql-data:
networks:
  mysqldb-network:
    name: mysqldb-network