version: '3.7'
services:
  spring-demo-cicd:
    container_name: spring-demo-cicd
    image: tuananh1810/spring-demo-cicd:${IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/${SPRING_DATASOURCE_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - ../.env
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mysqldb-network

  mysqldb:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${SPRING_DATASOURCE_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysqldb-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data:
networks:
  mysqldb-network:
    name: mysqldb-network