name: spring-demo-cicd
services:
  app:
    container_name: spring-demo-cicd
    image: tuananh1810/spring-demo-cicd:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env.app
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - mysqldb-network

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    env_file:
      - ../env/.env.db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysqldb-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data:
networks:
  mysqldb-network:
    name: mysqldb-network