name: spring-demo-cicd
services:
  app:
    container_name: spring-demo-cicd
    image: ${APP_IMAGE}
    ports:
      - "8080:8080"
    env_file:
      - ../env/.env.app
    depends_on:
      mysqldb:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - mysqldb-network

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - ../env/.env.db
    environment:
      - FLYWAY_UNDO_MIGRATIONS_ENABLED=true
    volumes:
      - ../src/main/resources/db/migrations:/flyway/migrations
    networks:
      - mysqldb-network
    # Run Flyway migrations
    entrypoint: [ "flyway", "-baselineOnMigrate=true", "-connectRetries=60", "-locations=filesystem:/flyway/migrations", "-validateMigrationNaming=true", "migrate" ]
    healthcheck:
      test: [ "CMD-SHELL", "flyway info | grep 'No errors'" ]
      retries: 10
      interval: 5s
      timeout: 30s

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    env_file:
      - ../env/.env.db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysqldb-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data:
networks:
  mysqldb-network:
    name: mysqldb-network